server:
  port: 9001
  servlet:
    context-path: /auth-server

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3307/secure
    username: authorization_user
    password: p@ssw0rd
    driver-class: org.mariadb.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl: validate
      dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: INFO
    org.springframework.security: TRACE